language: scala

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.sbt
    $HOME/.cache/coursier
