language: scala
jdk:
- openjdk8
- openjdk9

scala:
- 2.11.11
- 2.12.6

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.sbt
    $HOME/.ivy2
    target

jobs:
  include:
  - sudo: required
    language: bash
    jdk: ""
    scala: []
    env:
    - DOCKER_USERNAME=dani09
    - secure: "n3p9E6MmjwzQJbzVT5Ztf71z/QWN6FPEUG61mWiXS2XxHGqU+FlehWZALivcuN5FzhvVTYhYt8k04xf8FFp2WMhARNSO92wTXCz7M5D7oPiAYS2WABYXYzzUmw+i37SYDKe9UR50blSjtWIgaTMGkc44wK8ECTsnRYpXzSbUhFSVPGJFh6hImsUFeIIWDKSJGluwmKL+BF5vf62WEWB6Ioyr35deGaftn8cmeCPsNxFJpUE2F320xSV5paNJHm2A8aW9foE0A2SLqvV5owubI6TRSkm3Z3fiTOVs6QslCOVrbpqPjW/c01tnggPsRi8E9XNnYCuoZGikzyFS1Xym3x5O7Jf0IbzJ7xpE1gunJJ5JliQYIWhcBosuyqqUTd3DNDuOq94jrvle+dJzA0OxMy3sFVZiJAQAhZBg7JAkI5efJTd4Sbt9nCUhdMAuVftiVidSHtvVuCnY1GwUAE/eaZUClILi9ryX20QEJc9nwyTPArgg//j0o6rfp9gDJ+q+tJpjK2M7kBmAtqrA41FTc1mYdo2hrAlog9BswoCnlh0ZNBsPS1eZhKCArnq3FRKMS0NRHO6lSSz95jcj9upnhfeZg9odVHJc2wUv/sH9z07P+YnCSwwo5+vAytkx8hGYPCMTr+4sYgNdJZ3pEh8I7FD6lmrM/IFZgfwR8RCEnqY="
    script: |
      docker build . -f k8s/Dockerfiles/Dockerfile       -t dani09/movie-downloader
      docker build . -f k8s/Dockerfiles/nginx.Dockerfile -t dani09/movie-downloader:nginx
    deploy:
      provider: script
      script: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin && docker push dani09/movie-downloader
      on:
        branch: master

deploy:
  provider: releases
  api_key:
    secure: gQhidLU7K0+BZ7cWnvpyP415gL30Etca6k8d9q4NYRfnSVqddEzjtjyBtSEtXElGWM6jzWxjuKwyWBYZoaDdFhZD/WdpHTPcI1VPvR5XJiODwsap3O7p+PkCXXZPp8tOdL2wdfst7RnRmf29VZ0hSfAtmNipbsQnP2Rmrid0oNpymwDHtc77o4pTXkrSj90jHO99EWCCPnj5A99DzmzP0SIDK4Z7ncXC8lnS5eh+wzKY4kt0Kv+MAmWm28qRD8i0S7iUsd4mJUfptOY9X+dJLqN+GSbW6sldCjwtj/dAhRpH0eJcdtti7cQb3zGE3X6DoiCGb1At+kBE8UnjSWGenqK1le429UrOUGymZG5OjtMlpNxqKiOYHnEo4W/30vU1cYg1ByXGGdyFKgNpe+NcbE94ZatNGMKxswuTf6lF06XUWlCS4MPks9MizA9BrqTQZAUS0fjHlLiex1umYWYoIadGVye5lVYOcgzGYtNi/fERQopHcHV2L858P+V16GBJ0S7RgAGttS8tZ3yttwKDnFE0H7VAE8S2IdI8F7VLv3IjRYJvCB6v9z89Dn8kFIUtiPdpWXO1lrdKXvS/c9sp7OeWRoG+VFUav1TneVv/h/TCVPsT/XBiquKXQ/r+nB14DekZHPse3b+PavbU9+eQlEv8tNBHdp8hUQ10R8Rng+c=
  skip_cleanup: true
  file_glob: true
  file: build/libs/*
  on:
    repo: dani909/movie-downloader
    tags: true