apiVersion: skaffold/v1alpha3
kind: Config
build:
  tagPolicy:
    sha256: {}

  artifacts:
  - imageName: dani09/movie-downloader-dev
    workspace: .
    docker:
      dockerfilePath: k8s/Dockerfiles/Dockerfile

  - imageName: dani09/movie-downloader-dev-nginx
    workspace: .
    docker:
      dockerfilePath: k8s/Dockerfiles/nginx.Dockerfile

  local:
    skipPush: false
    #useDockerCLI: true
    #useBuildkit: true

deploy:
  kubectl:
    manifests:
    - k8s/manifests/dev-deployment.yaml
    - k8s/manifests/dev-deployment-ing.yaml
