apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: dani09/movie-downloader-dev
    context: .
    sync:
      'src/main/webapp/*': /src/main/webapp
    docker:
      dockerfile: k8s/Dockerfiles/dev.Dockerfile
  - image: dani09/movie-downloader-dev-nginx
    context: .
    docker:
      dockerfile: k8s/Dockerfiles/nginx.Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: true

deploy:
  kubectl:
    manifests:
    - k8s/manifests/dev-deployment.yaml
    - k8s/manifests/dev-deployment-ing.yaml
