apiVersion: skaffold/v1alpha3
kind: Config
build:
  tagPolicy:
    sha256: {}

  artifacts:
  - imageName: dani09/movie-downloader-dev
    workspace: .

  - imageName: dani09/movie-downloader-dev-nginx
    workspace: .
    docker:
      dockerfilePath: nginx.Dockerfile

  local:
    skipPush: false
    #useDockerCLI: true
    #useBuildkit: true

deploy:
  kubectl:
    manifests:
    - dev-deployment.yaml
    - dev-deployment-ing.yaml

# profiles section has all the profile information which can be used to override any build or deploy configuration
#profiles:
#- name: gcb
#  build:
#    googleCloudBuild:
#      projectId: k8s-skaffold
